Ingenimax/agent-sdk-go

pkg/llm/openai/client.go
Added concurrent execution for OpenAI parallel tool calls in the agent-sdk-go. This enhancement significantly improves performance by processing multiple tool calls simultaneously using goroutines and wait groups instead of sequential execution. The implementation maintains result order and properly handles error conditions without blocking other executions.
Tested using the StarOps Agent.
=> feat: implemented concurrent tool execution for OpenAI

examples/orchestration/agent_handoff/README.md, pkg/tools/websearch/websearch.go
docs(readme): update web search functionality instructions
This PR enhances the web search functionality documentation and improves the error reporting.
- Added a reference to the Google Custom Search API documentation for clarity.
- Included a direct link to the Programmable Search Engine Control Panel for easier management of search engines.
- Enhanced the error message in the web search tool to include the HTTP status text, providing better debugging information.
The changes primarily involve documentation updates and an improved error message. Manual verification of the updated README instructions and observing the enhanced error message during web search failures can confirm the changes.
=> docs(readme): update web search functionality instructions

pkg/agent/agent.go
Add agent description and getters
=> add agent description + getters

README.md, examples/llm/ollama/agent_integration/main.go, examples/llm/ollama/main.go, examples/llm/ollama/structured_output/README.md, examples/llm/ollama/structured_output/main.go, pkg/llm/ollama/README.md, pkg/llm/ollama/client.go, pkg/llm/ollama/client_test.go
- ✅ Full Ollama client implementation with native API endpoints
- ✅ Text generation with temperature, top-p, and stop sequence controls
- ✅ Model management (list, pull, unload) for local model handling
- ✅ System message support and structured output integration
- ✅ Comprehensive error handling and retry logic
- ✅ Complete documentation and examples
- New `pkg/llm/ollama/` package with client implementation
- Follows established SDK patterns (interfaces.LLM, options pattern)
- Includes unit tests and integration examples
- Supports Ollama's native `/api/` endpoints
- Compatible with agent framework and structured output
Tested with qwen3:0.6b
Please describe the tests that you ran to verify your changes. Provide instructions so we can …
=> feat: Add Ollama LLM provider support

README.md, docs/structured_output_yaml.md, examples/agent_config_yaml/main.go, examples/agent_config_yaml/tasks.yaml, pkg/agent/agent.go, pkg/agent/config.go, pkg/agent/config_test.go, pkg/agent/testdata/agents_with_structured_output.yaml
This PR adds structured output support for agents specified in YAML.
=> feat: add structured output support for agents specified in YAML

examples/embedding/advanced/main.go, examples/vectorstore/weaviate/README.md, examples/vectorstore/weaviate/main.go, pkg/interfaces/vectorstore.go, pkg/tracing/otel_langfuse.go, pkg/vectorstore/weaviate/weaviate.go, pkg/vectorstore/weaviate/weaviate_test.go
- Adjustments in weaviate implementation
- Add weaviate multi-tenant native support
- Fix Langfuse to receive full context
=> Weaviate adjustments + langfuse input fix

examples/memory/main.go, go.mod, go.sum, pkg/memory/redis_memory.go, pkg/memory/redis_memory_test.go
This PR introduces automatic conversation summarization capabilities to the Redis memory implementation, helping  manage long-running conversations more efficiently.
Changes:
• Automatic Summarization: Added ability to summarize old  messages when conversation length exceeds a configurable
threshold, reducing memory footprint while preserving  context
• LLM Integration: Integrated LLM client for generating  intelligent conversation summaries that maintain key information and context• Configurable Thresholds: Added  WithSummarization() option to configure message threshold and summary retention count
• Summary Management: Implemented summary storage with  automatic rotation to maintain a fixed number of historical
summaries
• Example Implementation: Added comprehensive example …
=> feat: Add Redis Memory Summarization Feature

examples/microservices/remote_timeout/main.go, pkg/agent/agent.go, pkg/grpc/client/remote_agent.go, pkg/grpc/server/agent_server.go, pkg/tools/agent_tool.go
- Expose timeout configuration for remote agents
- Increase default context timeout 
- Add remote call with auth support
=> fix: expose timeout configuration + add remote agent call with auth

pkg/agent/agent.go, pkg/agent/tool_memory_test.go, pkg/interfaces/llm.go, pkg/interfaces/memory.go, pkg/llm/anthropic/client.go, pkg/llm/openai/client.go, pkg/llm/vertex/client.go
- Add tool memory storage to maintain context across agent interactions when agent loop is enabled.
=> Add tool memory storage to maintain context across agent interactions

pkg/agent/agent.go, pkg/agent/format_test.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes # (issue)
=> fix: improve role format - memory

docs/loop_detection.md, pkg/llm/anthropic/client.go, pkg/llm/openai/client.go, pkg/llm/vertex/client.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes # (issue)
=> fix: add tools loop detection

pkg/llm/anthropic/sse.go, pkg/llm/anthropic/streaming.go, pkg/llm/gemini/streaming.go, pkg/llm/openai/streaming.go
Fix memory management when using streaming
=> fix: fix memory management when using streaming

pkg/grpc/client/remote_agent.go, pkg/grpc/client/remote_agent_test.go
Fix panic error on stream - nil content
=> Fix panic error on stream - nil content

pkg/llm/anthropic/streaming.go
- Adjusted Anthropic streaming
=> Fix Anthropic streaming

pkg/llm/anthropic/sse.go, pkg/llm/anthropic/streaming.go
Fix how internal iterations are handled when streaming
=> fix: anthropic streaming internal iterations

README.md, env.example, examples/llm/azureopenai/README.md, examples/llm/azureopenai/main.go, pkg/config/config.go, pkg/llm/azureopenai/README.md, pkg/llm/azureopenai/client.go, pkg/llm/azureopenai/client_test.go, pkg/llm/azureopenai/streaming.go
- Add complete Azure OpenAI LLM client implementation
- Support both endpoint URL and region-based configuration
- Implement streaming capabilities (GenerateStream, GenerateWithToolsStream)
- Add comprehensive reasoning support (prompt-based and native)
- Include tool calling with iterative loops and parallel execution
- Support structured output with JSON schema validation
- Add memory integration and tracing support
- Implement proper Azure-specific authentication and API versioning
- Include comprehensive unit tests and documentation
- Add working example with all features demonstrated
- Update configuration system with Azure OpenAI settings
- Set default API version to 2024-08-01-preview for structured output support
Features:
- Full interfaces.LLM implementation
- Dual client …
=> feat: Add Azure OpenAI client with comprehensive features

examples/custom_functions/README.md, examples/custom_functions/main.go, pkg/agent/agent.go, pkg/agent/custom_functions_test.go, pkg/agent/streaming.go
Add custom functions for agents allowing the replacement of the default agent behavior with your own custom logic while still having access to all agent components (LLM, memory, tools, logger, etc.).
=> Add custom functions for agents/microservice

go.mod, pkg/agent/agent.go, pkg/grpc/client/remote_agent.go, pkg/llm/anthropic/client.go, pkg/llm/anthropic/vertex.go, pkg/llm/anthropic/vertex_test.go, pkg/structuredoutput/utils.go
- Add Anthropic Vertex retry with multiple regions
- Fix Anthropic structured output support
- Fix context cancelled issue when using grpc / microservice wrapper
=> Anthropic Vertex regions retry, fix context cancelled issue, fix Anthropic structured output

pkg/llm/anthropic/client.go
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context.
Fixes # (issue)
=> Add new sonnet 4.5 model to supported thinking

pkg/llm/anthropic/streaming.go, pkg/tracing/langfuse.go, pkg/tracing/otel_llm_middleware.go
Fix langfuse streaming integration.
=> fix langfuse streaming integration
